# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170226_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetail',
            name='slug',
        ),
    ]
