# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_postdetail_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='slug',
            field=models.SlugField(default='foobar', max_length=150),
        ),
    ]
