# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-26 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postdetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
