# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170302_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=128),
        ),
    ]
